#pragma once

#include <stdint.h>

namespace rcq
{
	enum RES_DATA : uint32_t
	{
		RES_DATA_ENVIRONMENT_MAP_GEN_MAT,
		RES_DATA_ENVIRONMENT_MAP_GEN_SKYBOX,
		RES_DATA_GBUFFER_GEN,
		RES_DATA_DIR_SHADOW_MAP_GEN,
		RES_DATA_SS_DIR_SHADOW_MAP_GEN,
		RES_DATA_IMAGE_ASSEMBLER,
		RES_DATA_SKY_DRAWER,
		RES_DATA_SUN_DRAWER,
		RES_DATA_TERRAIN_DRAWER,
		RES_DATA_TERRAIN_TILE_REQUEST,
		RES_DATA_WATER_COMPUTE,
		RES_DATA_WATER_DRAWER,
		RES_DATA_REFRACTION_MAP_GEN,
		RES_DATA_SSR_RAY_CASTING,
		RES_DATA_COUNT
	};
}