#pragma once

#include <stdint.h>

namespace rcq
{
	enum RES_IMAGE : uint32_t
	{
		RES_IMAGE_ENVIRONMENT_MAP_GEN_DEPTHSTENCIL,
		RES_IMAGE_ENVIRONMENT_MAP,
		RES_IMAGE_GB_POS_ROUGHNESS,
		RES_IMAGE_GB_BASECOLOR_SSAO,
		RES_IMAGE_GB_METALNESS_SSDS,
		RES_IMAGE_GB_NORMAL_AO,
		RES_IMAGE_GB_DEPTH,
		RES_IMAGE_DIR_SHADOW_MAP,
		RES_IMAGE_SS_DIR_SHADOW_MAP,
		RES_IMAGE_SSAO_MAP,
		RES_IMAGE_PREIMAGE,
		RES_IMAGE_PREV_IMAGE,
		RES_IMAGE_REFRACTION_IMAGE,
		RES_IMAGE_SSR_RAY_CASTING_COORDS,
		RES_IMAGE_BLOOM_BLUR,
		RES_IMAGE_COUNT
	};
}